# Generated by Django 4.2.8 on 2023-12-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carro",
            name="ano",
            field=models.BigIntegerField(max_length=12),
        ),
    ]
